"""
Config compartilhado - FIELD_VISIBILITY e funções para tipos de memorando.

Contém mapeamento de visibilidade de campos e helpers para seções/campos por tipo.
"""

FIELD_VISIBILITY = {
    "identification": {
        "searcher_name": ["Short Memo - Co-investimento (Search Fund)"],
        "investor_nationality": ["Short Memo - Co-investimento (Search Fund)"],
        "fip_casca": ["Short Memo - Co-investimento (Search Fund)"],
        "search_start_date": ["Short Memo - Co-investimento (Search Fund)"],
        "gestora_name": ["Short Memo - Co-investimento (Gestora)"],
        "gestora_fundacao": ["Short Memo - Co-investimento (Gestora)"],
        "aum_total": ["Short Memo - Co-investimento (Gestora)"],
        "aum_fundo_especifico": ["Short Memo - Co-investimento (Gestora)"],
        "veiculo_coinvestimento": ["Short Memo - Co-investimento (Gestora)"],
        "data_oportunidade": ["Short Memo - Co-investimento (Gestora)"],
        "setor": ["Short Memo - Co-investimento (Gestora)"],
        "company_name": "ALL",
        "company_location": "ALL",
        "business_description": "ALL",
        "company_founding_year": ["Short Memo - Primário"],
        "deal_context": "ALL",
    },
    "transaction_structure": {
        "currency": "ALL",
        "stake_pct": "ALL",
        "equity_value_mm": "ALL",
        "ev_mm": "ALL",
        "multiple_ev_ebitda": "ALL",
        "multiple_reference_period": "ALL",
        "total_transaction_value_mm": "ALL",
        "multiple_total": "ALL",
        "cash_payment_mm": "ALL",
        "cash_pct_total": "ALL",
        "equity_cash_mm": "ALL",
        "seller_note_mm": "ALL",
        "seller_note_pct_total": "ALL",
        "seller_note_tenor_years": "ALL",
        "seller_note_index": "ALL",
        "seller_note_frequency": "ALL",
        "seller_note_grace": "ALL",
        "seller_note_terms": "ALL",
        "earnout_mm": "ALL",
        "earnout_conditions": "ALL",
        "earnout_timeline": "ALL",
        "step_up_mm": "ALL",
        "acquisition_debt_mm": "ALL",
        "acquisition_debt_rate": "ALL",
        "acquisition_debt_tenor_years": "ALL",
        "acquisition_debt_institution": "ALL",
        "leverage_resulting_x": "ALL",
        "multiple_with_earnout": "ALL",
        "debt_equity_ratio": "ALL",
        "investor_opinion": ["Short Memo - Co-investimento (Search Fund)", "Short Memo - Co-investimento (Gestora)"],
        "valuation_total_empresa": ["Short Memo - Co-investimento (Gestora)"],
        "participacao_total_adquirida": ["Short Memo - Co-investimento (Gestora)"],
        "participacao_fundo_gestora": ["Short Memo - Co-investimento (Gestora)"],
        "participacao_coinvestimento": ["Short Memo - Co-investimento (Gestora)"],
        "valor_total_coinvestimento": ["Short Memo - Co-investimento (Gestora)"],
        "alocacao_fundo": ["Short Memo - Co-investimento (Gestora)"],
        "disponivel_coinvestidores": ["Short Memo - Co-investimento (Gestora)"],
        "cheque_spectra": ["Short Memo - Co-investimento (Gestora)"],
        "cheque_spectra_pct": ["Short Memo - Co-investimento (Gestora)"],
        "assentos_conselho": ["Short Memo - Co-investimento (Gestora)"],
        "vesting_lockup": ["Short Memo - Co-investimento (Gestora)"],
        "materias_protegidas": ["Short Memo - Co-investimento (Gestora)"],
        "tag_along": ["Short Memo - Co-investimento (Gestora)"],
        "drag_along": ["Short Memo - Co-investimento (Gestora)"],
        "opcoes_liquidez": ["Short Memo - Co-investimento (Gestora)"],
        "compensacao_dividendos": ["Short Memo - Co-investimento (Gestora)"],
    },
    "financials_history": {
        "revenue_current_mm": "ALL",
        "revenue_cagr_pct": "ALL",
        "revenue_cagr_period": "ALL",
        "revenue_base_year": "ALL",
        "revenue_base_year_mm": "ALL",
        "ebitda_current_mm": "ALL",
        "ebitda_margin_current_pct": "ALL",
        "ebitda_cagr_pct": ["Short Memo - Primário"],
        "ebitda_base_year_mm": ["Short Memo - Primário"],
        "net_debt_mm": "ALL",
        "leverage_net_debt_ebitda": "ALL",
        "cash_conversion_pct": ["Short Memo - Co-investimento (Search Fund)", "Short Memo - Co-investimento (Gestora)", "Short Memo - Primário"],
        "gross_margin_pct": ["Short Memo - Co-investimento (Gestora)", "Short Memo - Primário"],
        "opex_pct_revenue": ["Short Memo - Co-investimento (Search Fund)", "Short Memo - Primário"],
        "employees_count": ["Short Memo - Co-investimento (Search Fund)", "Short Memo - Primário"],
        "financials_commentary": "ALL",
    },
    "saida": {
        "cenario_base_ano_saida": "ALL",
        "cenario_base_cagr_receita_pct": "ALL",
        "cenario_base_margem_ebitda_pct": "ALL",
        "cenario_base_multiplo_saida_x": "ALL",
        "cenario_base_multiplo_saida_ano": "ALL",
        "cenario_base_dividend_yield_pct": "ALL",
        "cenario_base_tir_pct": "ALL",
        "cenario_base_moic": "ALL",
        "cenario_alternativo_ano_saida": "ALL",
        "cenario_alternativo_cagr_receita_pct": "ALL",
        "cenario_alternativo_margem_ebitda_pct": "ALL",
        "cenario_alternativo_multiplo_saida_x": "ALL",
        "cenario_alternativo_multiplo_saida_ano": "ALL",
        "cenario_alternativo_dividend_yield_pct": "ALL",
        "cenario_alternativo_tir_pct": "ALL",
        "cenario_alternativo_moic": "ALL",
        "cenario_base_tir_bruta_pct": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_base_moic_bruto": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_base_tir_liquida_pct": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_base_moic_liquido": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_base_dividendos_periodo": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_alternativo_tir_bruta_pct": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_alternativo_moic_bruto": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_alternativo_tir_liquida_pct": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_alternativo_moic_liquido": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_alternativo_dividendos_periodo": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_conservador_ano_saida": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_conservador_cagr_receita_pct": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_conservador_margem_ebitda_pct": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_conservador_multiplo_saida_x": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_conservador_multiplo_saida_ano": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_conservador_dividendos_periodo": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_conservador_tir_bruta_pct": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_conservador_moic_bruto": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_conservador_tir_liquida_pct": ["Short Memo - Co-investimento (Gestora)"],
        "cenario_conservador_moic_liquido": ["Short Memo - Co-investimento (Gestora)"],
        "taxa_gestao_pct": ["Short Memo - Co-investimento (Gestora)"],
        "taxa_performance_pct": ["Short Memo - Co-investimento (Gestora)"],
        "saida_observacoes": "ALL",
    },
    "returns": {
        "irr_pct": "ALL",
        "moic": "ALL",
        "holding_period_years": "ALL",
        "entry_multiple": "ALL",
        "returns_commentary": "ALL",
    },
    "qualitative": {
        "business_model": "ALL",
        "competitive_advantages": "ALL",
        "key_risks": "ALL",
        "next_steps": ["Short Memo - Co-investimento (Search Fund)", "Short Memo - Co-investimento (Gestora)", "Short Memo - Primário"],
        "main_competitors": "ALL",
        "competitor_count": ["Short Memo - Co-investimento (Search Fund)", "Short Memo - Co-investimento (Gestora)", "Short Memo - Primário"],
        "market_share_pct": ["Short Memo - Co-investimento (Gestora)", "Short Memo - Primário"],
        "market_fragmentation": ["Short Memo - Co-investimento (Search Fund)", "Short Memo - Co-investimento (Gestora)", "Short Memo - Primário"],
        "market_overview": "ALL",
        "management_team": "ALL",
        "growth_strategy": "ALL",
        "esg_considerations": "ALL",
        "qualitative_commentary": "ALL",
    },
    "opinioes": {
        "founders_opinion": ["Short Memo - Primário"],
        "founders_track_record": ["Short Memo - Primário"],
        "founders_comparison": ["Short Memo - Primário"],
        "company_positioning_opinion": ["Short Memo - Primário"],
        "market_reputation": ["Short Memo - Primário"],
        "spectra_recommendation": "ALL",
        "key_strengths": "ALL",
        "key_concerns": "ALL",
        "investment_rationale": "ALL",
        "next_steps": ["Short Memo - Co-investimento (Search Fund)", "Short Memo - Co-investimento (Gestora)", "Short Memo - Primário"],
    },
    "gestora": {
        "gestora_nome": ["Short Memo - Primário"],
        "gestora_ano_fundacao": ["Short Memo - Primário"],
        "gestora_localizacao": ["Short Memo - Primário"],
        "gestora_tipo": ["Short Memo - Primário"],
        "gestora_aum_mm": ["Short Memo - Primário"],
        "gestora_num_fundos": ["Short Memo - Primário"],
        "gestora_socios_principais": ["Short Memo - Primário"],
        "gestora_filosofia_investimento": ["Short Memo - Primário"],
        "track_record": ["Short Memo - Co-investimento (Gestora)"],
        "principais_exits": ["Short Memo - Co-investimento (Gestora)"],
        "equipe": ["Short Memo - Co-investimento (Gestora)"],
        "estrategia_investimento": ["Short Memo - Co-investimento (Gestora)"],
        "tese_gestora": ["Short Memo - Co-investimento (Gestora)"],
        "performance_historica": ["Short Memo - Co-investimento (Gestora)"],
        "relacionamento_anterior_spectra": ["Short Memo - Co-investimento (Gestora)"],
    },
    "fundo": {
        "fundo_nome": ["Short Memo - Primário"],
        "fundo_vintage": ["Short Memo - Primário"],
        "fundo_closing": ["Short Memo - Primário"],
        "fundo_moeda": ["Short Memo - Primário"],
        "fundo_target_mm": ["Short Memo - Primário"],
        "fundo_hard_cap_mm": ["Short Memo - Primário"],
        "fundo_status_captacao": ["Short Memo - Primário"],
        "fundo_primeiro_closing_data": ["Short Memo - Primário"],
        "fundo_primeiro_closing_target_mm": ["Short Memo - Primário"],
        "fundo_captado_mm": ["Short Memo - Primário"],
        "fundo_percentual_levantado": ["Short Memo - Primário"],
        "fundo_commitment_spectra_mm": ["Short Memo - Primário"],
        "fundo_commitment_spectra_pct": ["Short Memo - Primário"],
        "fundo_periodo_investimento_anos": ["Short Memo - Primário"],
        "fundo_vida_total_anos": ["Short Memo - Primário"],
    },
    "estrategia": {
        "estrategia_tese": ["Short Memo - Primário"],
        "estrategia_setores": ["Short Memo - Primário"],
        "estrategia_geografia": ["Short Memo - Primário"],
        "estrategia_estagio": ["Short Memo - Primário"],
        "estrategia_numero_ativos_alvo": ["Short Memo - Primário"],
        "estrategia_ticket_medio_mm": ["Short Memo - Primário"],
        "estrategia_ticket_min_mm": ["Short Memo - Primário"],
        "estrategia_ticket_max_mm": ["Short Memo - Primário"],
        "estrategia_tipo_participacao": ["Short Memo - Primário"],
        "estrategia_alocacao": ["Short Memo - Primário"],
        "estrategia_diferenciacao": ["Short Memo - Primário"],
    },
    "estrutura_veiculo": {
        "duracao_fundo_anos": ["Short Memo - Co-investimento (Gestora)"],
        "capital_autorizado": ["Short Memo - Co-investimento (Gestora)"],
        "taxa_gestao_veiculo_pct": ["Short Memo - Co-investimento (Gestora)"],
        "taxa_performance_veiculo_pct": ["Short Memo - Co-investimento (Gestora)"],
        "hurdle_rate": ["Short Memo - Co-investimento (Gestora)"],
        "catch_up": ["Short Memo - Co-investimento (Gestora)"],
        "evento_equipe_chave": ["Short Memo - Co-investimento (Gestora)"],
        "quorum_destituicao_pct": ["Short Memo - Co-investimento (Gestora)"],
        "chamadas_capital": ["Short Memo - Co-investimento (Gestora)"],
        "pontos_atencao_regulamento": ["Short Memo - Co-investimento (Gestora)"],
    },
    "spectra_context": {
        "spectra_is_existing_lp": ["Short Memo - Primário"],
        "spectra_previous_funds": ["Short Memo - Primário"],
        "spectra_vehicle": ["Short Memo - Primário"],
        "spectra_relacao_historica": ["Short Memo - Primário"],
        "spectra_relacionamento": ["Short Memo - Primário"],
        "spectra_commitment_target_mm": ["Short Memo - Primário"],
        "spectra_commitment_pct": ["Short Memo - Primário"],
        "spectra_closing_alvo": ["Short Memo - Primário"],
        "spectra_coinvestidores": ["Short Memo - Primário"],
        "spectra_allocation_strategy": ["Short Memo - Primário"],
        "spectra_due_diligence": ["Short Memo - Primário"],
        "spectra_termos_negociados": ["Short Memo - Primário"],
        "spectra_fees_terms": ["Short Memo - Primário"],
        "spectra_governance": ["Short Memo - Primário"],
    },
    "gestor": {
        "searcher_name": ["Memorando - Co-investimento (Search Fund)"],
        "searcher_background": ["Memorando - Co-investimento (Search Fund)"],
        "searcher_experience": ["Memorando - Co-investimento (Search Fund)"],
        "searcher_assessment": ["Memorando - Co-investimento (Search Fund)"],
        "searcher_complementarity": ["Memorando - Co-investimento (Search Fund)"],
        "searcher_references": ["Memorando - Co-investimento (Search Fund)"],
        "searcher_track_record": ["Memorando - Co-investimento (Search Fund)"],
    },
    "projections_table": {
        "projections_years": ["Memorando - Co-investimento (Search Fund)"],
        "projections_base_case": ["Memorando - Co-investimento (Search Fund)"],
        "projections_upside_case": ["Memorando - Co-investimento (Search Fund)"],
        "projections_downside_case": ["Memorando - Co-investimento (Search Fund)"],
        "projections_assumptions_base": ["Memorando - Co-investimento (Search Fund)"],
        "projections_assumptions_upside": ["Memorando - Co-investimento (Search Fund)"],
        "projections_assumptions_downside": ["Memorando - Co-investimento (Search Fund)"],
    },
    "returns_table": {
        "returns_base_case": ["Memorando - Co-investimento (Search Fund)"],
        "returns_upside_case": ["Memorando - Co-investimento (Search Fund)"],
        "returns_downside_case": ["Memorando - Co-investimento (Search Fund)"],
        "returns_sensitivity_table": ["Memorando - Co-investimento (Search Fund)"],
        "returns_exit_scenarios": ["Memorando - Co-investimento (Search Fund)"],
    },
    "board_cap_table": {
        "board_members": ["Memorando - Co-investimento (Search Fund)"],
        "cap_table": ["Memorando - Co-investimento (Search Fund)"],
        "governance_structure": ["Memorando - Co-investimento (Search Fund)"],
        "board_commentary": ["Memorando - Co-investimento (Search Fund)"],
    },
}


def get_relevant_fields_for_memo_type(memo_type: str) -> dict:
    relevant_fields = {}
    for section, fields in FIELD_VISIBILITY.items():
        relevant_fields[section] = []
        for field_key, visibility_config in fields.items():
            if visibility_config == "ALL":
                relevant_fields[section].append(field_key)
            elif isinstance(visibility_config, list) and memo_type in visibility_config:
                relevant_fields[section].append(field_key)
    return {k: v for k, v in relevant_fields.items() if v}


def get_sections_for_memo_type(memo_type: str) -> list:
    if memo_type == "Short Memo - Primário":
        return ["gestora", "fundo", "estrategia", "spectra_context", "opinioes"]
    elif memo_type == "Memorando - Co-investimento (Search Fund)":
        return [
            "identification",
            "gestor",
            "transaction_structure",
            "financials_history",
            "projections_table",
            "returns_table",
            "board_cap_table",
            "qualitative",
            "opinioes",
        ]
    else:
        return [
            "identification",
            "transaction_structure",
            "financials_history",
            "saida",
            "qualitative",
            "opinioes",
        ]


def get_field_count_for_memo_type(memo_type: str) -> dict:
    relevant = get_relevant_fields_for_memo_type(memo_type)
    by_section = {section: len(fields) for section, fields in relevant.items()}
    return {
        "total": sum(by_section.values()),
        "by_section": by_section,
    }
